### ISSUE TITLE
Allure TestNG Docker

### ISSUE THREAD

**Issue by garyc0221** [fescobar/allure-docker-service#157]
I'm currently trying to generate a report from the TestNG sample directory. 
When running docker-compose up -d allure allure-ui from the directory I am getting this error for the default project.
```ALLURE_VERSION: 2.13.8
Generating default report
Overriding configuration
Checking Allure Results every 1 second/s
Creating executor.json for PROJECT_ID: default
/app/generateAllureReport.sh: line 59: /app/allure-docker-api/static/projects/default/results/executor.json: Permission denied
Generating report for PROJECT_ID: default
[INFO] /app/allure-docker-api/app.py:290 Setting SECURITY_ENABLED=0 by default
Could not generate report
java.nio.file.AccessDeniedException: /app/allure-docker-api/static/projects/default/reports/latest
at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
at java.base/java.nio.file.Files.createDirectory(Unknown Source)
at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
at java.base/java.nio.file.Files.createDirectories(Unknown Source)
at io.qameta.allure.CommonJsonAggregator.aggregate(CommonJsonAggregator.java:51)
at io.qameta.allure.CompositeAggregator.aggregate(CompositeAggregator.java:43)
at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:53)
at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:70)
at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
at io.qameta.allure.Commands.generate(Commands.java:104)
at io.qameta.allure.CommandLine.run(CommandLine.java:152)
at io.qameta.allure.CommandLine$$Lambda$11/0000000098345F10.get(Unknown Source)
at java.base/java.util.Optional.orElseGet(Unknown Source)
at io.qameta.allure.CommandLine.main(CommandLine.java:88)
ls: cannot access '/app/allure-docker-api/static/projects/default/reports/*': No such file or directory
Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
Detecting results changes for PROJECT_ID: default
Automatic Execution in Progress for PROJECT_ID: default...
Creating history on results directory for PROJECT_ID: default ...
mkdir: cannot create directory ‘/app/allure-docker-api/static/projects/default/results/history’: Permission denied
Creating executor.json for PROJECT_ID: default
/app/generateAllureReport.sh: line 57: /app/allure-docker-api/static/projects/default/results/executor.json: Permission denied
Generating report for PROJECT_ID: default
Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
Could not generate report
java.nio.file.AccessDeniedException: /app/allure-docker-api/static/projects/default/reports/latest
at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
at java.base/java.nio.file.Files.createDirectory(Unknown Source)
at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
at java.base/java.nio.file.Files.createDirectories(Unknown Source)
at io.qameta.allure.CommonJsonAggregator.aggregate(CommonJsonAggregator.java:51)
at io.qameta.allure.CompositeAggregator.aggregate(CompositeAggregator.java:43)
at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:53)
at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:70)
at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
at io.qameta.allure.Commands.generate(Commands.java:104)
at io.qameta.allure.CommandLine.run(CommandLine.java:152)
at io.qameta.allure.CommandLine$$Lambda$11/00000000683428B0.get(Unknown Source)
at java.base/java.util.Optional.orElseGet(Unknown Source)
at io.qameta.allure.CommandLine.main(CommandLine.java:88)
ls: cannot access '/app/allure-docker-api/static/projects/default/reports/latest': No such file or directory
ls: cannot access '/app/allure-docker-api/static/projects/default/reports/*': No such file or directory
Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
```

**Comment by fescobar** [comment]
https://github.com/fescobar/allure-docker-service/issues/108

**Comment by mr-possible** [comment]
I assume you are using Windows machine as this is likely to occur in there. So I would suggest you to install any Ubuntu LTS from app store and configure docker to use that WSL distro and not the default one. Things should get sorted.
