### ISSUE TITLE
ls: cannot access '/app/allure-docker-api/static/projects/default/reports': No such file or directory

### ISSUE THREAD

**Issue by nashoshinoda** [fescobar/allure-docker-service#228]
Good day, Frank

I know this is a redundant topic in the repository but probably I'm missing something else that wasn't mentioned in previous issues closed. I have a VM with Centos7 where I have installed Jenkins 2.401.3, Docker 24.0.5, and Docker-compose 1.23.2 as well.
Following the instructions in your documentation about [multiple projects](https://github.com/fescobar/allure-docker-service#multiple-project---docker-compose), I customized the docker-compose.yml with my setup:

This is my docker-compose.yml file:
```yaml
version: '3'

services:
  allure:
    image: "docker.io/frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 366
    ports:
      - "5050:5050"
    volumes:
      - /reports/projects:/app/projects
    restart: unless-stopped

  allure-ui:
    image: "docker.io/frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://10.233.134.242:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"
    restart: unless-stopped

volumes:
  allure:
    external: true
```

Then, I ran the command sudo docker-compose up getting these errors:
```bash
Creating api_auto-allure-1    ... done
Creating api_auto-allure-ui-1 ... done
Attaching to api_auto_allure-ui_1, api_auto_allure_1
allure-ui_1  | ALLURE_UI_VERSION: 7.0.3
allure-ui_1  | ALLURE_DOCKER_API_URL=http://10.233.134.242:5050/allure-docker-service
allure-ui_1  | ROUTER_BASE_NAME=/allure-docker-service-ui
allure_1     | Not checking results automatically
allure_1     | ALLURE_VERSION: 2.21.0
allure_1     | Generating default report
allure_1     | ls: cannot access '/app/allure-docker-api/static/projects/default/reports': No such file or directory
allure_1     | Creating results directory for PROJECT_ID: default
allure_1     | Creating executor.json for PROJECT_ID: default
allure_1     | mkdir: cannot create directory ‘/app/allure-docker-api/static/projects/default’: Permission denied
allure_1     | /app/generateAllureReport.sh: line 59: /app/allure-docker-api/static/projects/default/results/executor.json: No such file or directory
allure_1     | Generating report for PROJECT_ID: default
allure_1     | [INFO] /app/allure-docker-api/app.py:294 Setting SECURITY_ENABLED=0 by default
allure_1     | /app/allure-docker-api/static/projects/default/results does not exist
allure_1     | Could not generate report
allure_1     | java.nio.file.AccessDeniedException: /app/allure-docker-api/static/projects/default
allure_1     |  at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
allure_1     |  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
allure_1     |  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
allure_1     |  at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
allure_1     |  at java.base/java.nio.file.Files.createDirectory(Unknown Source)
allure_1     |  at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
allure_1     |  at java.base/java.nio.file.Files.createDirectories(Unknown Source)
allure_1     |  at io.qameta.allure.CommonJsonAggregator.aggregate(CommonJsonAggregator.java:51)
allure_1     |  at io.qameta.allure.CompositeAggregator.aggregate(CompositeAggregator.java:43)
allure_1     |  at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:53)
allure_1     |  at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:70)
allure_1     |  at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
allure_1     |  at io.qameta.allure.Commands.generate(Commands.java:103)
allure_1     |  at io.qameta.allure.CommandLine.run(CommandLine.java:160)
allure_1     |  at io.qameta.allure.CommandLine$$Lambda$96/00000000484717E0.get(Unknown Source)
allure_1     |  at java.base/java.util.Optional.orElseGet(Unknown Source)
allure_1     |  at io.qameta.allure.CommandLine.main(CommandLine.java:92)
allure_1     | ls: cannot access '/app/allure-docker-api/static/projects/default/reports/*': No such file or directory
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Timeout requesting  after 7 attempts
allure_1     | 2023-08-16 17:02:47.799:INFO::main: Logging initialized @294ms to org.eclipse.jetty.util.log.StdErrLog

```

Checking the documentation again, I found you included a section about [Override the user container](https://github.com/fescobar/allure-docker-service#override-user-container) so I included the instruction user: 1000:1000 in the allure and allure-ui services like this but getting the same errors:
```yaml
version: '3'

services:
  allure:
    image: "docker.io/frankescobar/allure-docker-service"
    user: 1000:1000
    environment:
      ...

  allure-ui:
    image: "docker.io/frankescobar/allure-docker-service-ui"
    user: 1000:1000
    environment:
    ...
```

```bash
Creating api_auto_allure-ui_1 ... done
Creating api_auto_allure_1    ... done
Attaching to api_auto_allure_1, api_auto_allure-ui_1
allure_1     | Not checking results automatically
allure_1     | ALLURE_VERSION: 2.21.0
allure_1     | Generating default report
allure_1     | ls: cannot access '/app/allure-docker-api/static/projects/default/reports': No such file or directory
allure_1     | Creating results directory for PROJECT_ID: default
allure_1     | mkdir: cannot create directory ‘/app/allure-docker-api/static/projects/default’: Permission denied
allure_1     | Creating executor.json for PROJECT_ID: default
allure_1     | /app/generateAllureReport.sh: line 59: /app/allure-docker-api/static/projects/default/results/executor.json: No such file or directory
allure_1     | Generating report for PROJECT_ID: default
allure-ui_1  | ALLURE_UI_VERSION: 7.0.3
allure-ui_1  | ALLURE_DOCKER_API_URL=http://10.233.134.242:5050/allure-docker-service
allure-ui_1  | ROUTER_BASE_NAME=/allure-docker-service-ui
allure_1     | [INFO] /app/allure-docker-api/app.py:294 Setting SECURITY_ENABLED=0 by default
allure_1     | /app/allure-docker-api/static/projects/default/results does not exist
allure_1     | Could not generate report
allure_1     | java.nio.file.AccessDeniedException: /app/allure-docker-api/static/projects/default
allure_1     |  at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
allure_1     |  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
allure_1     |  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
allure_1     |  at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
allure_1     |  at java.base/java.nio.file.Files.createDirectory(Unknown Source)
allure_1     |  at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
allure_1     |  at java.base/java.nio.file.Files.createDirectories(Unknown Source)
allure_1     |  at io.qameta.allure.CommonJsonAggregator.aggregate(CommonJsonAggregator.java:51)
allure_1     |  at io.qameta.allure.CompositeAggregator.aggregate(CompositeAggregator.java:43)
allure_1     |  at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:53)
allure_1     |  at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:70)
allure_1     |  at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
allure_1     |  at io.qameta.allure.Commands.generate(Commands.java:103)
allure_1     |  at io.qameta.allure.CommandLine.run(CommandLine.java:160)
allure_1     |  at io.qameta.allure.CommandLine$$Lambda$96/00000000804790F0.get(Unknown Source)
allure_1     |  at java.base/java.util.Optional.orElseGet(Unknown Source)
allure_1     |  at io.qameta.allure.CommandLine.main(CommandLine.java:92)
allure_1     | ls: cannot access '/app/allure-docker-api/static/projects/default/reports/*': No such file or directory
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Timeout requesting  after 7 attempts
allure_1     | 2023-08-16 17:08:32.240:INFO::main: Logging initialized @295ms to org.eclipse.jetty.util.log.StdErrLog
```

Another approach was adding the user I'm using to access through SSH in the docker group but same thing. Also, I checked the /etc/passwd file to get the data from it and the values are 1010:100. I made the update in my docker-compose.yml file but the results were the same.

As an additional information, if I access to the allure-docker-service container, I'm able to go to `allure-docker-api/static/projects/default/reports`, the allure user has ownership in the directories and, from the VM side, the user jenkins with the directories of my project.

Any clue about something I'm missing of need to do? Please, let me know if you need further information. Thank you so much for the time to read this and your future response.

Regards.

**Comment by nashoshinoda** [comment]
Please, dismiss this question. I had to create the volume Allure and placed the docker-compose.yml file to run it.

**Comment by fescobar** [comment]
No problem.
Thanks for the info.
