### ISSUE TITLE
Status Code 413 when sending highpayload

### ISSUE THREAD

**Issue by chikiendiep** [fescobar/allure-docker-service#247]
`Hi,` 

When using the send_result.py script, and we have heavy reports files with many screenshots, the http post request to send the report to the allure server returns status code 413.

I put API_RESPONSE_LESS_VERBOSE: 1 but it still doesn't work.

Please check. Best regards,
```
Traceback (most recent call last):
  File "/builds/myeline/cnomtestauto/send_results.py", line 54, in <module>

------------------SEND-RESULTS------------------
STATUS CODE:
413
RESPONSE:
    json_response_body = json.loads(response.content)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

docker-compose-allure.yml file:
```
version: '3'
services:
    allure:
        image: "frankescobar/allure-docker-service:latest"
        user: root
        environment:
            CHECK_RESULTS_EVERY_SECONDS: NONE
            KEEP_HISTORY: 1
            KEEP_HISTORY_LATEST: 7
            API_RESPONSE_LESS_VERBOSE: 1
        ports:
            - "5050:5050"
        volumes:
            - ${PWD}/projects:/app/projects
        restart: always

    allure-ui:
        image: "frankescobar/allure-docker-service-ui:latest"
        user: root
        environment:
            ALLURE_DOCKER_PUBLIC_API_URL: "http://172.21.0.1:5050"
            ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
        ports:
            - "5252:5252"
        restart: always
```

**Comment by fescobar** [comment]
Just split the content into different requests.

**Comment by shun198** [comment]
This is how I solved the highpayload problem

```send_results.sh
#!/bin/bash

# This directory is where you have all your results locally, generally named as `allure-results`
ALLURE_RESULTS_DIRECTORY='allure-results'
# This url is where the Allure container is deployed. We are using localhost as example
ALLURE_SERVER='http://localhost:5050'
# Project ID according to existent projects in your Allure container - Check endpoint for project creation >> `[POST]/projects`
PROJECT_ID='test-proj'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
FILES_TO_SEND=$(ls -dp $DIR/$ALLURE_RESULTS_DIRECTORY/* | grep -v /$)

if [ -z "$FILES_TO_SEND" ]; then
  exit 1
fi

FILES=''
COUNT=0
for FILE in $FILES_TO_SEND; do
  FILES+="-F files[]=@$FILE "
  COUNT+=1
  if [ $COUNT -gt 99 ]; then
    set -x
    echo "------------------SEND-RESULTS------------------"
    curl -X POST "$ALLURE_SERVER/allure-docker-service/send-results?project_id=$PROJECT_ID" -H 'Content-Type: multipart/form-data' $FILES -ik
    set +x
    FILES=''
    COUNT=0
  fi
done

#set -o xtrace
#echo "------------------SEND-RESULTS------------------"
#curl -X POST "$ALLURE_SERVER/allure-docker-service/send-results?project_id=$PROJECT_ID" -H 'Content-Type: multipart/form-data' $FILES -ik


#If you want to generate reports on demand use the endpoint `GET /generate-report` and disable the Automatic Execution >> `CHECK_RESULTS_EVERY_SECONDS: NONE`
#echo "------------------GENERATE-REPORT------------------"
#EXECUTION_NAME='execution_from_my_bash_script'
#EXECUTION_FROM='http://google.com'
#EXECUTION_TYPE='bamboo'

#You can try with a simple curl
#RESPONSE=$(curl -X GET "$ALLURE_SERVER/allure-docker-service/generate-report?project_id=$PROJECT_ID&execution_name=$EXECUTION_NAME&execution_from=$EXECUTION_FROM&execution_type=$EXECUTION_TYPE" $FILES)
#ALLURE_REPORT=$(grep -o '"report_url":"[^"]*' <<< "$RESPONSE" | grep -o '[^"]*$')

#OR You can use JQ to extract json values -> https://stedolan.github.io/jq/download/
#ALLURE_REPORT=$(echo $RESPONSE | jq '.data.report_url')
```
