### ISSUE TITLE
Permission denied /app/generateAllureReport.sh:

### ISSUE THREAD

**Issue by Renkar** [fescobar/allure-docker-service#99]
So  when  i  use Single Project - Docker Compose

docker-compose up -d allure
 
in docker logs i see  error

/app/generateAllureReport.sh: line 56: /app/allure-docker-api/static/projects/default/results/executor.json: Permission denied
Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
Could not generate report
java.nio.file.AccessDeniedException: /app/allure-docker-api/static/projects/default/reports/latest
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
        at java.base/java.nio.file.Files.createDirectory(Unknown Source)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
        at java.base/java.nio.file.Files.createDirectories(Unknown Source)
        at io.qameta.allure.CommonJsonAggregator.aggregate(CommonJsonAggregator.java:51)
        at io.qameta.allure.CompositeAggregator.aggregate(CompositeAggregator.java:43)
        at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:53)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:70)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
        at io.qameta.allure.Commands.generate(Commands.java:104)
        at io.qameta.allure.CommandLine.run(CommandLine.java:152)
        at io.qameta.allure.CommandLine$$Lambda$9/00000000AC39C980.get(Unknown Source)
        at java.base/java.util.Optional.orElseGet(Unknown Source)
        at io.qameta.allure.CommandLine.main(CommandLine.java:88)
ls: cannot access '/app/allure-docker-api/static/projects/default/reports/latest': No such file or directory
ls: cannot access '/app/allure-docker-api/static/projects/default/reports/*': No such file or directory

**Comment by Renkar** [comment]
Find  copy this issue

**Comment by fescobar** [comment]
https://github.com/fescobar/allure-docker-service/issues/97
